collabora/libsurvive

- redist/linmath.c
- tools/lighthousefind_tori/main.c
- tools/lighthousefind_tori/tori_includes.h
- tools/lighthousefind_tori/torus_localizer.c
This is a pretty big change to how the solution is calculated.  I'm no longer using point clouds at all, and have transitioned to only using a gradient descent.  I've also definitely gotten out of the "clean math" and into the "engineering" mentality with this commit.  
The gradient to the solution appears to be a very steep valley, so a basic gradient descent tends to zig zag horribly.  I modified the algorithm in a way that is working surprisingly well to race to the minimum.
I had a nasty issue where an undesirably local minimum existed near the origin.  Through some empirical testing I found that I could beautifully even out the distortion using a sine curve multiplier.  I have no idea why it works, but the data goes from looking horrible to nearly perfect, so I'm guessing there's …
> Optimize gradient descent

- calibrate.c
- include/libsurvive/survive.h
- redist/json_helpers.c
- redist/os_generic.h
- redist/symbol_enumerator.c
- src/survive.c
- src/survive_config.c
- src/survive_vive.c
- winbuild/calibrate/calibrate.vcxproj
- winbuild/calibrate/calibrate.vcxproj.filters
- winbuild/libsurvive.sln
- winbuild/libsurvive/ReadMe.txt
- winbuild/libsurvive/libsurvive.vcxproj
- winbuild/libsurvive/libsurvive.vcxproj.filters
Adds capability to build libsurvive using Visual Studio 2017 Community Edition
Currently only building libsurvive and calibrate.  Will add more if this is approved.
This builds libsurvive as a static library.  If anybody wants to add a build target to also build a dll, I'm A-OK with that.
After way too much beating my head against the wall, reading that it's not possible, and trying a bunch of possible work-arounds, I gave up on trying to get the link-time registration of plugins to work.  Instead, I added a few lines to survive_init to register them, #ifdef'd for _WIN32.
> VS2017 CE Support

- src/poser_turveytori.c
The world reference frame is set by the position of the tracked object during calibration.  Currently not using the IMU, so make sure the tracked object's +Z is facing directly up. 
Also added orientation to the pose finding.  Haven't built the tooling to test if the orientation is right, so it's probably wrong.  But, it's a start.
> Not Wonky World Reference Frame

- include/libsurvive/poser.h
- include/libsurvive/survive.h
- include/libsurvive/survive_types.h
- redist/os_generic.c
- src/survive_data.c
Minor changes to allow libsurvive to be called from C++: added extern "C" declarations in the externally visible headers, and cleaned up the header function prototypes.   This doesn't hurt plain C at all, and fixes several warnings.
> Initial C++ client support

- src/poser_turveytori.c
I've been seeing starvation that manifests itself as weird light data coming into the disambiguator.  A major cause ended up being starvation.  This change will cut the frequency of poser calls by by 75%
> Reduce Poser Calls

- redist/linmath.c
- src/poser_turveytori.c
quattomatrix33() needed to be updated after the fix in quatfrom2vectors
Additional poser updates to make it more robust.
Poser is now updating based on both lighthouses.  Expect significant jitter from this.
> Fix Tori Poser

- calibrate.c
- include/libsurvive/survive.h
- src/survive.c
- src/survive_cal.c
Change adds a config option for the number of "active" lighthouses,
which can be 1.  Calibrate will run with a single lighthouse
if the new config option LighthouseCount is set to 1.
> Add support for using only 1 lighthouse

- include/libsurvive/survive.h
- src/survive.c
- src/survive_vive.c
Adds infrastructure that captures button & trackpad inputs.  Those inputs are placed into a circular queue, and processed on a different thread to avoid starvation on the thread reading from USB or Wireless.  Currently, they're only printed out in that new thread, but I'll add a callback to allow a consumer to register for those events, just like they'd get light capture data or IMU data.
> Add support for buttons

- src/ootx_decoder.c
- src/survive_cal.c
- src/survive_cal.h
- src/survive_vive.c
One patch fixes all the unaligned accesses I'd found. There maybe more. This doesn't matter so much on x86, but could be a problem for ARM cpus. There is maybe a more centralized location for the unaligned access structures to go. These were found with "address=sanitize address=undefined" flags. 
The other one is a slight buffer overrun.
> Fixed two minor / potential bugs

- src/ootx_decoder.c
- src/survive_vive.c
Also renamed the wrapper types to make it clear which was unsigned and which was signed
> Fixed inadvertent change to signedness of acceldata type

- Makefile
- data_recorder.c
- include/libsurvive/survive_types.h
- src/survive_default_devices.c
- src/survive_default_devices.h
- src/survive_internal.h
- src/survive_playback.c
- src/survive_vive.c
This adds a playback driver option. 
- data_recorder now takes an argument which specifies where to put the recorded data. You can still redirect stdout, but it might have messages that the playback parser will barf on. 
- usb driver doesn't register its poll/close events if there are no USB devices
- 'PlaybackDir' config.json option now exists; it should point to the _directory_ which contains the following:
- events - A file named events with the output of data-recorder
- *_config.json - The raw HTC configuration file from whatever devices were captured. 
Be sure when testing playback to unplug any actual devices; as both streams will be active at once and nothing will work very well. 
Further areas:
- Might need a better way to make sure drivers aren't sending conflicting data; …
> Playback driver

- include/libsurvive/survive.h
- src/survive.c
Looked into changing the default but might have knock-on effects with either people already set up and running, and also with the linmath.h file. 
This seems like a good last resort solution. It exits at runtime when you call survive_init if the user compiled with inconsistent flags. 
An easy way to test this currently is to make, rm test, edit the Makefile to remove -DUSE_DOUBLE and make test. When you run test now, it'll exit immediately with an error message whereas before it'd return nonsensical values.
> Added a check at init that makes sure the user agrees with what FLT is

- Makefile
- include/libsurvive/survive_reproject.h
- src/poser_charlesslow.c
- src/survive_cal.c
- src/survive_reproject.c
It also gives an option to calculate reprojection error after every calibration, while fixing charlesslow to work with the new standard.
> This adds reprojection functionality to the library

- LICENSE
Background:
The relevant code in OSVR-Vive-Libre should have been largely migrated to https://github.com/lubosz/OpenHMD/tree/lighthouse/src/drv_htc_vive by now. Currently it still has LGPLv3 headers but I believe the intention of the current development is to get it into OpenHMD under OpenHMD's permissive license.
Unfortunately libsurvive does not clarify which code exactly this paragraph applies to and it might even be hard to find out which parts it still applies to after a long time with many changes.
In effect, potential users who require a library under a permissive license might be hesitant to use libsurvive or code from libsurvive (ironically some concerns come from OpenHMD).
Before this pull request is merged it would be great if the authors of the OSVR-Vive-Libre code can comment …
> remove forced-source license notice

- README.md
Added section showing from blinking cursor to get libsurvive, compile and run calibrate, including what to do if you run into missing dependency.
> Added info about possible dependency

- redist/json_helpers.c
- redist/json_helpers.h
- src/survive_default_devices.c
- src/test_cases/watchman.c
Turns out I had a nasty bug in my code and went on a wild goose chase. The lightcap data is as we expect it to be, only at a different endpoint. This commit adds non-HIDAPI access to a 2018 Tracker (called a TRACKER1 in the code) and pulls button, IMU and light data from it over USB. It also reads the new "head" element from the JSON configuration file.
> Tracker 2018 usb

- src/driver_usbmon.c
```
libsurvive/src/driver_usbmon.c:510:36: error: unknown type name '_IO_off64_t'; did you mean '__off64_t'?
510 | int gzip_cookie_seek(void *cookie, _IO_off64_t *pos, int __w) { return gzseek((gzFile)cookie, *pos, __w); }
|                                    ^~~~~~~~~~~
|                                    __off64_t
```
https://sourceware.org/git/?p=glibc.git;a=commit;h=9964a14579e5eef925aaa82facc4980f627802fe
> fix IO_off64_t datatype after glibc update

- src/driver_vive.c
This is the only complaint during runtime I saw in valgrind (see commit description). Not sure if there's a reason strlen() instead of the len from zlib deflate was used, but for me it works.
> make valgrind happy by not using strlen()

- redist/CMakeLists.txt
On Archlinux libx11 installs
/usr/include/X11/Xlib.h, not /usr/include/X11/xlib.h
> fix xlib header case

- include/libsurvive/survive_api.h
- src/survive_api.c
The SurviveSimpleObject_type was never set to HMD, because to figure out
if a device is an HMD, the config parsing needed to be triggered from
the usb polling.
Now the type will be kept at unknown until it can be updated to an
actual type. The application will have to wait for the type to be
available before knowing which device is which.
> api: update device type once available

- .travis.yml
- travis-exclusion.lst
(You'll wanna crunch these down into a single commit on merge)
This'll need some work for however you want to set it up, but it'll deploy a release for both Windows and Linux (the Linux build has an exclusion list to avoid grabbing all the CMake guff as it doesn't have a separate build folder). This will probably also need some tweaking before merging
My recommendation would be disabling email notifications and enabling Discord webhooks:  https://github.com/DiscordHooks/travis-ci-discord-webhook
This only deploys tags right now too.
> Travis Build Deployment

- CMakeLists.txt
- survive.pc.in
I don't know if this works for windows, if not we can guard it with
```if(CMAKE_SYSTEM_NAME STREQUAL "Linux")``` or so.
With this PR I can build a standalone `api_example.c` with this simple CMakeLists.txt
```cmake
project(survivetest C)
cmake_minimum_required(VERSION 3.6)
add_executable(survivetest api_example.c)
find_package(PkgConfig REQUIRED)
pkg_check_modules(SURVIVE REQUIRED IMPORTED_TARGET survive)
target_link_libraries(survivetest PRIVATE PkgConfig::SURVIVE)
```
> Support installing libsurvive

- CMakeLists.txt
- src/CMakeLists.txt
Without this linking to libsurvive would fail for e.g. Monado (at least on Alpine Linux):
```
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lsurvive
```
> Include library version in libsurvive target

- useful_files/81-vive.rules
udev doesn't allow rules to have comments on the end
[   35.253978] udevd[2752]: invalid key/value pair in file /usr/lib/udev/rules.d/81-vive.rules on line 23, starting at character 82 ('#')
[   35.253982] udevd[2752]: hint: comments can only start at beginning of line
[   35.253989] udevd[2752]: invalid key/value pair in file /usr/lib/udev/rules.d/81-vive.rules on line 24, starting at character 82 ('#')
[   35.253991] udevd[2752]: hint: comments can only start at beginning of line
[   35.253998] udevd[2752]: invalid key/value pair in file /usr/lib/udev/rules.d/81-vive.rules on line 25, starting at character 82 ('#')
[   35.254000] udevd[2752]: hint: comments can only start at beginning of line
[   35.254006] udevd[2752]: invalid key/value pair in file /usr/lib/udev/rules.d/81-vive.rules …
> Put comments in the udev file on a new line

- bindings/cs/UnityViewer/Assets/SurviveObject.cs
Just a small check for disposal when exiting Unity. Without this, it's going to crash when Alt+F4-ing out of a build, and (maybe) crash Unity itself when stopping from the editor. 
I am not completely sure about needing all of `Close`, `Dispose` and `= null`.
> Added disposal on exit in the Unity example

- bindings/cs/libsurvive.net/SurviveAPI.cs
The C# Demo app, and generally C# code, crashes after some time with:
``A callback was made on a garbage collected delegate of type 'libsurvive.net!libsurvive.SurviveSimpleLogFn::Invoke``
this could be after several minutes of runtime. It happens because C# does not see a reference for the log function in the managed side, although it still exists in the native context, so it collects it and then tries to call it.
A simple fix is to just assign a SurviveSimpleLogFn delegate in the SurviveAPI class, so as to keep the handle on the C# side.
Tried it for over an hour of runtime and it works fine.
> Fixed garbage collection of SurviveSimpleLogFn delegate

- redist/CNFGWinDriver.c
- redist/dirent.windows.h
- redist/linmath.c
- redist/linmath.h
- redist/lintest.c
- redist/mpfit/mpfit.c
- src/barycentric_svd/barycentric_svd.c
- src/lfsr.c
- src/lfsr_lh2.c
- src/poser_barycentric_svd.c
- src/poser_general_optimizer.c
- src/poser_mpfit.c
- src/survive_kalman.c
- src/survive_kalman_tracker.c
- src/survive_optimizer.c
- src/test_cases/check_generated.c
- src/test_cases/kalman.c
- src/test_cases/test_replays.c
- survive-solver.c
`malloc.h` is not present on FreeBSD/macOS, don't try to include it
> Fix build on systems with no malloc.h (FreeBSD and macOS)

- CMakeLists.txt
This enables building on stock Ubuntu 18.04 without any obvious issues.
> lower cmake requirement to 3.10

- bindings/python/pysurvive/pysurvive_generated.py
- include/libsurvive/survive.h
According to C99 standard, section 6.2.6.2, signed one bit field may actually hold only sign bit
> Change signed one bit field to unsigned

- README.md
They linked to the SVG, now they link to the relevant workflow
> Fixed Badge Links in Readme

- src/survive_api.c
> survive_api: button event now uses global time

- src/survive_default_devices.c
As tested with a HTC Vive Pro Eye + Wand controllers, this removes a warning about unknown headset name for the "T20" device.
More importantly it fixes input mappings of the Wand controllers delivered with the HMD:
- Grip buttons now work. Before they were dead.
- Menu buttons now work. Before they were dead.
- Touching the touchpad correctly registers as touch instead of click.
> Improve detection/handling of HTC Vive Pro Eye + Wand controllers.

- src/driver_vive.c
- src/driver_vive.hidapi.h
Fixes #283 and set the size of magic buffers used for the wireless dongle. This is needed otherwise we only get -1 and can't complete the setup.
Not sure if these changes works on Linux. It would be nice if someone with Linux could test before merging.
> Fix windows wireless dongle setup

- README.md
- Change to https git URL, since SSH requires extra configuration.
- `udevadm trigger` needs to be run a root as well.
- APT should be updated before installing to prevent an outdated package cache.
- Change to `apt` since it is shorter.
> Update Debian build instruction in README.md

- src/driver_usbmon.c
`off64_t` is not a language defined type and is not available everywhere. Instead the function should use `z_off_t` which is defined by zlib (and is most likely `off_t`).
> src/driver_usbmon: replace off64_t by z_off_t

- src/driver_vive.c
Tested with a Vive Pro controller on 1.0 and 2.0 Lighthouses
with a 3rd party Watchman dongle running version 1526689969 
on Windows
Before fix error occured: "Could not send raw mode to WM0 -1"
> change buffer size to 64 to allow protocol switching on windows

- src/survive_sensor_activations.c
Initialize two variables before accessing them in a goto block for logging.
Fixes build warnings like these:
```
In file included from /usr/include/stdio.h:970,
from /usr/include/malloc.h:25,
from /home/spacy/src/libsurvive/redist/linmath.h:7,
from /home/spacy/src/libsurvive/include/libsurvive/survive_types.h:5,
from /home/spacy/src/libsurvive/include/libsurvive/poser.h:4,
from /home/spacy/src/libsurvive/include/libsurvive/survive.h:5,
from /home/spacy/src/libsurvive/src/survive_sensor_activations.c:4:
In function ‘snprintf’,
inlined from ‘SurviveSensorActivations_check_outlier’ at /home/spacy/src/libsurvive/src/survive_sensor_activations.c:183:3:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:68:10: warning: ‘measured_dev’ may be used uninitialized [-Wmaybe-uninitialized]
68 |   return …
```
> Fix build warning: Initialize variables before logging
