collabora/libsurvive

.gitignore, Makefile, tools/disambiguate/.gitignore, tools/disambiguate/Makefile, tools/disambiguate/disambiguate.c, tools/planetest/.gitignore
My first shot at a disambiguator ... will try to clean it up, make it usable after sleep and work.
=> Disambiguate

Makefile, include/disambiguator.h, include/survive.h, src/disambiguator.c, src/survive_data.c, tools/disambiguate/Makefile, tools/disambiguate/disambiguate.c
Now integrated and compiling. Cannot test it though, I got no vive ...
=> New disambiguator integrated

include/survive.h, src/disambiguator.c, src/disambiguator.h, src/survive_data.c, tools/disambiguate/Makefile, tools/disambiguate/disambiguate.c, tools/disambiguate/disambiguate2.c
I finally was able to take the time to document and fix my implementation of the disambiguator. It is not currently enabled by default.
I also added a comment about the "theory" behind it on top of the `disambiguator.c` file.
=> disambiguator

README.md
Created a table which includes an updated URL collection of the archieved YouTube livestreams
=> Update URL collection of YouTube livestreams

tools/lighthousefind_tori/torus_localizer.c, tools/lighthousefind_tori/visualization.c
Improves modularity and changes the estimation refinement from using point clouds to using a gradient descent.  Results in much faster calculations and better estimates.
=> Using gradient descent to refine estimate

redist/linmath.h, tools/lighthousefind_tori/main.c, tools/lighthousefind_tori/torus_localizer.c
Started optimizing  the code by minimizing trig functions and caching some frequently used values.  Also removed the point cloud functions, as they were starting to get in the way of the optimizations.  
Total time to acquire lighthouse positions is cut by more than half with this commit.
=> find_tori optimizations and old code removal

include/libsurvive/survive.h, src/poser_octavioradii.c, src/poser_turveytori.c, winbuild/libsurvive/libsurvive.vcxproj, winbuild/libsurvive/libsurvive.vcxproj.filters
Right now, these are only being built on Windows.  Keeping it that way for now so I don't have to worry about breaking linux yet...
=> Adding posers

include/libsurvive/poser.h, src/poser_octavioradii.c, src/poser_turveytori.c, src/survive_data.c, src/survive_process.c, src/survive_vive.c
Functional Tori Poser, with a lot of crud lying around that needs to be cleaned up.
=> Tori poser home stretch

src/poser_turveytori.c
Establishes a world view.  Unfortunately, the plane that represents the ground in the world view is not parallel to the physical ground.  And it really needs to be.
=> Wonky World View

src/poser_turveytori.c, src/survive_data.c
This feature removes the requirement that you calibrate
with the tracked object in any particular orientation.
The IMU on the tracked object will be used to determine
what direction is "up"
=> Use the IMU to determine +Z

calibrate.c, src/poser_turveytori.c
Also updated the visualization in calibrate.c to show
position & orientation as calculated by each lighthouse
at the same time
=> Fix the orientation from ToriPoser

redist/linmath.c, redist/linmath.h, src/poser_turveytori.c
some improvement to rotation part of pose
Still not working quite right
=> Modest updates to Tori

calibrate.c, src/poser_turveytori.c
Displays lighthouse poses in calibrate view, and fixes some display issues
=> Display Lighthouse Poses in calibrate.c

src/poser_turveytori.c
This definitely works a little better. There are still issues.
=> Small change to orientation

src/poser_turveytori.c, src/survive.c, src/survive_cal.c, src/survive_config.c
Added some config options.  Changed a few defaults.  Better printed output format from PoserTurveyTori.
Hopefully, this will make it easier for someone new to get up and running more easily.
=> Configuration Changes

calibrate.c, redist/linmath.c, redist/linmath.h, src/poser_turveytori.c
Significant improvements in tracking by removing some axis-angle calculations and replacing with quaternion (still some more changes needed there)
Additional feature to use the accelerometer to determine "up" instead of requiring tracked object's +z face up during calibration.
=> Make tracking good

src/survive_vive.c
--Upon startup, Watchman1 (wireless only) will do a short
haptic feedback/ vibration.
--Also have some POC code that turns off the controller (currently disabled)
--Thank you Nairol!
=> Haptic POC

include/libsurvive/survive.h, include/libsurvive/survive_types.h, src/survive.c, src/survive_process.c, src/survive_vive.c
Fully plumbed support for controller buttons
Also, commented haptic call because it messed with the vive_magic calls, given where I had it.
=> Controller Buttons Fully Implemented

include/libsurvive/survive.h, include/libsurvive/survive_types.h, src/survive.c, src/survive_process.c, src/survive_vive.c
The plumbing is now in place for the haptic call.
Left in place a "demo" where haptic is called when a controller's trigger is pulled
=> Haptic Call Plumbed

include/libsurvive/survive.h, include/libsurvive/survive_types.h, src/poser_turveytori.c, src/survive.c, src/survive_data.c, src/survive_process.c, test.c
Added a standard way for a poser to report raw (per-lighthouse) pose.
Updated test.c to run calibrate so it can be used as a demo
=> Provide standard way for posers to report pose output

src/survive_vive.c
Longer term, need to determine why if failed and fix root cause.
=> Remove dependency on GetSem to fix linux segfault

src/survive_process.c, test.c
Hopefully, this will make it easier for anyone wanting to use libsurvive
to have a simple starting point for doing so.
=> A few changes to test.c

src/survive_vive.c
Pretty sure this was just a copy paste mistake
=> Fixed typo which broke tr0 callbacks

README.md
As suggested in https://github.com/cnlohr/libsurvive/issues/97
=> add usage information to readme

src/survive_default_devices.c
=> Added nullptr checks around file access

data_recorder.c, src/ootx_decoder.c, src/survive.c, src/survive_config.c, src/survive_vive.c, winbuild/libsurvive/libsurvive.vcxproj, winbuild/libsurvive/libsurvive.vcxproj.filters
The position bit save/ restore should fix the ability to use a saved calibration.
=> Fix MSVC & Fix Saving & Restoring PositionSet bit

Makefile, include/libsurvive/poser.h, include/libsurvive/survive.h, include/libsurvive/survive_types.h, src/poser.c, src/poser_charlesslow.c, src/poser_turveytori.c, src/survive.c, src/survive_cal.c, src/survive_process.c, test.c
This adds an additional user level callback to notify them when lighthouses are found.
It also passes in hooks that posers can call to set LH / poser position. The idea here is that no poser sets LH or so pose directly, but instead calls the PoserData callbacks. This will let us chain together different poser strategies
=> Poser callbacks

redist/os_generic.h, redist/os_generic.unix.h, sensors-readout.c, src/driver_udp.c, src/survive_plugins.c
Set of changes that allow build on macOS 
MSG_NOSIGNAL issue fix blatantly ripped of from https://github.com/cntools/cnping/pull/47/files
=> Fix build on macOS

useful_files/81-vive.rules
Seems I missed a line in ad967baf30519ee3323878c0a3432e240a2675f7
=> Put comment in the udev file on a new line

CMakeLists.txt, cmake/FindEigen3.cmake
Fixed a few warnings and eigen dependency search
=> Fix cmake build

bindings/python/example.py
show position and rotation instead of the Pose object instance id
=> make example.py more straightforward

Makefile
=> fix "cmake: Unknown argument -j4"

src/driver_vive.c
Bandaid patch for sensor data being lost on linux devices as of 464dd97 (#294)
Refactor touched area
=> Fix sensor data loss on linux caused by 464dd97 (#294)
